version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: softwareDesignPattern-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - TZ=Asia/Tehran
    networks:
      - softwareDesignPattern

  #db:
  # image: mysql:8.0.3
  #  container_name: softwareDesignPattern-db
  #  tty: true
  #  restart: unless-stopped
  #  ports:
  #    - 3311:3306
  #  environment:
  #    SERVICE_TAGS: dev
  #    SERVICE_NAME: mysql
  #    TZ: "Asia/Tehran"
  #  volumes:
  #    - ./docker/db/designpattern.sql:/docker-entrypoint-initdb.d/1.sql
  #    - ./docker/db/dbData:/var/lib/mysql
  #  command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci' ]
  #  networks:
  #    - softwareDesignPattern

  nginx:
    image: nginx:stable-alpine
    container_name: softwareDesignPattern-nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "3070:80"
    environment:
      - TZ=Asia/Tehran
    depends_on:
      - app
      #- db
      #- phpmyadmin
    networks:
      - softwareDesignPattern

  #phpmyadmin:
  #  image: phpmyadmin:5.2.1
  #  restart: unless-stopped
  #  container_name: softwareDesignPattern-pma
  #  ports:
  #    - "3071:80"
  #  environment:
  #    - PMA_HOST=db
  #    - PMA_PMADB=pmadb
  #    - TZ=Asia/Tehran
  #  depends_on:
  #    - db
  #  networks:
  #    - softwareDesignPattern

  composer:
    image: composer:2
    container_name: softwareDesignPattern-composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      - TZ=Asia/Tehran
    depends_on:
      - app
    command: [ "composer", "install" ]
    networks:
      - softwareDesignPattern


networks:
  softwareDesignPattern:
    driver: bridge
